CREATE DATABASE RALOS;
USE RALOS;

CREATE TABLE CLIENTES (
ID_CLIENTE INT AUTO_INCREMENT NOT NULL,
NOME_CLIENTE VARCHAR (100) NOT NULL, 
CPF VARCHAR (14) NOT NULL,
ENDERECO VARCHAR (100) NOT NULL,
DATA_NASC DATETIME,
PRIMARY KEY (ID_CLIENTE)
);

CREATE TABLE EQUIPAMENTOS (
COD_EQUIPAMENTO INT AUTO_INCREMENT NOT NULL,
NOME_EQUIPAMENTO VARCHAR (100) NOT NULL,
DESCRICAO VARCHAR (255) NOT NULL,
VALOR_ALUGUEL DECIMAL (10,2) NOT NULL,
QUANTIDADE INT,
PRIMARY KEY (COD_EQUIPAMENTO)
);

CREATE TABLE FORNECEDORES (
ID_FORNECEDOR INT AUTO_INCREMENT NOT NULL,
NOME_FORNECEDOR VARCHAR (100) NOT NULL,
CNPJ VARCHAR (17) NOT NULL,
CIDADE VARCHAR (100) NOT NULL,
ESTADO CHAR (2) DEFAULT 'SP',
PRIMARY KEY (ID_FORNECEDOR)
);

CREATE TABLE COMPRA (
ID_COMPRA INT AUTO_INCREMENT NOT NULL,
COD_EQUIPAMENTO INT NOT NULL, 
ID_CLIENTE INT NOT NULL,
FOREIGN KEY (COD_EQUIPAMENTO) REFERENCES EQUIPAMENTOS(COD_EQUIPAMENTO),
FOREIGN KEY (ID_CLIENTE) REFERENCES CLIENTES(ID_CLIENTE),
PRIMARY KEY (ID_COMPRA)
);

CREATE TABLE VENDE (
ID_VENDA INT AUTO_INCREMENT NOT NULL,
ID_FORNECEDOR INT NOT NULL,
COD_EQUIPAMENTO INT NOT NULL,
FOREIGN KEY (ID_FORNECEDOR) REFERENCES FORNECEDORES(ID_FORNECEDOR),
FOREIGN KEY (COD_EQUIPAMENTO) REFERENCES EQUIPAMENTOS(COD_EQUIPAMENTO),
PRIMARY KEY (ID_VENDA)
);

