CREATE DATABASE IF NOT EXISTS SOLAR; -- cria database
USE SOLAR; -- usa database

-- TABELA CLIENTES
CREATE TABLE IF NOT EXISTS CLIENTES (
  COD_CLIENTE INT AUTO_INCREMENT NOT NULL, -- auto incrementa o valor ao cod_cliente
  NOME_CLIENTE VARCHAR(100),
  CPF VARCHAR(14) NOT NULL, -- not null não permite não receber algum valor 
  ENDERECO VARCHAR(100), 
  CELULAR VARCHAR(19),
  PRIMARY KEY (COD_CLIENTE)
);

-- TABELA FORNECEDORES
CREATE TABLE IF NOT EXISTS FORNECEDORES (
  ID_FORNECEDOR INT AUTO_INCREMENT NOT NULL,
  NOME_FORNECEDOR VARCHAR(100),
  CELULAR VARCHAR(19),
  CIDADE VARCHAR(100),
  CNPJ VARCHAR(18) NOT NULL,
  ENDERECO VARCHAR(100),
  ESTADO CHAR(2) DEFAULT 'SP' NOT NULL, -- default preenche automaticamente com 'sp', caso não acha nada
  PRIMARY KEY (ID_FORNECEDOR) -- define a chave primária como 'ID_FORNECEDOR'
);

-- TABELA PRODUTOS
CREATE TABLE IF NOT EXISTS PRODUTOS (
  COD_PRODUTO INT AUTO_INCREMENT NOT NULL,
  NOME_PRODUTO VARCHAR(100) NOT NULL,
  QUANTIDADE INT,
  DESCRICAO VARCHAR(100),
  VALOR DECIMAL(10,2) NOT NULL, -- define que o valor pode ser de até 10 digitos com 2 numeros após a virgula 
  PRIMARY KEY (COD_PRODUTO)
);

-- para melhor esquema crie as relações após a criação das tabelas, exemplo 'comprar' depois de ter criado, produto e cliente.
-- TABELA COMPRAR
CREATE TABLE IF NOT EXISTS COMPRAR (
  COD_VENDA INT AUTO_INCREMENT NOT NULL,
  COD_CLIENTE INT NOT NULL,
  COD_PRODUTO INT NOT NULL,
  PRIMARY KEY (COD_VENDA),
  FOREIGN KEY (COD_CLIENTE) REFERENCES CLIENTES(COD_CLIENTE), -- define que 'cod_cliente' é uma chave extrangeira derivada da tabela clientes e o input do 'COD_CLIENTES'
  FOREIGN KEY (COD_PRODUTO) REFERENCES PRODUTOS(COD_PRODUTO)
);

-- TABELA VENDER
CREATE TABLE IF NOT EXISTS VENDER (
  COD_VENDA INT AUTO_INCREMENT NOT NULL,
  COD_PRODUTO INT NOT NULL,
  ID_FORNECEDOR INT NOT NULL,
  PRIMARY KEY (COD_VENDA),
  FOREIGN KEY (COD_PRODUTO) REFERENCES PRODUTOS(COD_PRODUTO),
  FOREIGN KEY (ID_FORNECEDOR) REFERENCES FORNECEDORES(ID_FORNECEDOR)
);

CREATE TABLE IF NOT EXISTS FUNCIONARIOS (
ID_FUNCIONARIO INT AUTO_INCREMENT NOT NULL,
NOME_CLIENTE VARCHAR (100) NOT NULL,
DATA_NASC DATETIME NOT  NULL,
DATA_ADMISSAO DATETIME NOT NULL,
SALARIO DECIMAL (5,2) NOT NULL,
CARGO VARCHAR (100) NOT NULL,
CPF VARCHAR (14) NOT NULL,
COD_DEPARTAMENTO INT NOT NULL,
FOREIGN KEY (COD_DEPARTAMENTO) REFERENCES DEPARTAMENTO (COD_DEPARTAMENTO),
PRIMARY KEY (ID_FUNCIONARIO)
);

CREATE TABLE IF NOT EXISTS DEPARTAMENTO(
COD_DEPARTAMENTO INT AUTO_INCREMENT NOT NULL,
NOME_DEPARTAMENTO VARCHAR (100) NOT NULL,
LOCAL_DEPARTAMENTO VARCHAR(100),
FUNCIONARIOS VARCHAR (100),
DESCRICAO VARCHAR (255),
PRIMARY KEY (COD_DEPARTAMENTO)
);


-- Consulta tabelas
SELECT * FROM EMPREGADO;

-- ALTERAÇÕES EM TABELAS 
ALTER TABLE FUNCIONARIOS
ADD SEXO CHAR (1);

-- EXCLUIR UMA COLUNA ESPECIFICA
ALTER TABLE FUNCIONARIOS
DROP COLUMN SEXO;

-- ALTERA O NOME DA TABELA FUNCIONARIOS PARA EMPREGADO
ALTER TABLE FUNCIONARIOS
RENAME TO EMPREGADO;

ALTER TABLE EMPREGADO 
MODIFY COLUMN NOME_CLENTE VARCHAR(200);

ALTER TABLE FORNECEDORES
MODIFY COLUMN ESTADO CHAR (2) DEFAULT 'MG';

ALTER TABLE EMPREGADO
ADD PRIMARY KEY (CPF);



