CREATE DATABASE loja_limpeza;

USE loja_limpeza;

CREATE TABLE Produtos (
ID_PRODUTO INT PRIMARY KEY auto_increment,
NOME_PRODUTO VARCHAR (100),
IMAGEM_PRODUTO BLOB,
VALOR DECIMAL (10,2),
DESCRICAO VARCHAR (255)
);

CREATE TABLE Cliente (
ID_CLIENTE INT PRIMARY KEY AUTO_INCREMENT,
NOME_CLIENTE VARCHAR (100),
IDADE INT,
CPF VARCHAR (14),
USER VARCHAR (100)
);

CREATE TABLE Pedidos (
ID_PEDIDOS INT PRIMARY KEY AUTO_INCREMENT,
DATA_PEDIDO DATETIME,
NOME_CLIENTE VARCHAR (100),
QUANTIDADE_PRODUTO INT,
VALOR_PRODUTO DECIMAL (10, 2)
); 

CREATE TABLE Funcionarios (
ID_FUNCIONARIO INT PRIMARY KEY AUTO_INCREMENT,
NOME_FUNCIONARIO VARCHAR (100),
DATA_NASC DATE,
CARGO VARCHAR(100),
RG VARCHAR (12)
);

CREATE TABLE Estoque (
ID_ESTOQUE INT PRIMARY KEY AUTO_INCREMENT,
NOME_PRODUTO VARCHAR (100),
LOCAL_PRODUTO VARCHAR (100),
VALIDADE DATETIME,
QUANTIDADE INT
);




